### ISSUE TITLE
Transfer `@stencil/helmet` to `@stencil-community/helmet`

### ISSUE THREAD

**Issue by mikaelkaron** [stencil-community/proposals#4]
## Package Request

**Name**: `@stencil/helmet`

**Package**: `@stencil-community/helmet`

### Description

Simply a transfer of the old `@stencil/helmet` package to `@stencil-community/helmet`

**Comment by rwaskiewicz** [comment]
Hey @mikaelkaron 👋 

This is something that we'd be open to doing. Moving this package to the community would require us to find/set up a maintainer for the package - would you or someone you know be interested?

**Comment by mikaelkaron** [comment]
I could be convinced to maintain ;) What exactly are the expectations of a maintainer?

**Comment by rwaskiewicz** [comment]
We (Ionic/Stencil team) try to give maintainers a pretty high degree of autonomy - from a set of expectations, we expect a maintainer to keep an eye on the repo/code. Specifically:
- Triaging issues/feature requests
- Reviewing any code that comes in from the community
- Releasing new versions of the software, following semantic versioning

We would also require 2FA to be enabled on your npm account.

Myself/the Stencil team are around as a form of escape hatch/backup in the event that you’d need any outside intervention of some sort/conflict resolution. But like I said, we’d like to give community maintainers as much autonomy as they’d like.

Let me know if you have any questions!

**Comment by mikaelkaron** [comment]
Let's do it. When do we start?

**Comment by rwaskiewicz** [comment]
Awesome! The way this'll work will required:
- Me to unarchive the repo, and to transfer it to the stencil-community GitHub org
- Get you set up with the repo in GitHub to mange the code
- Me to do a little npm configuration and to add you to the stencil-community NPM org.

Are you on the Ionic/Stencil Discord? If so, can you send me your Discord username so I can verify your email?

**Comment by rwaskiewicz** [comment]
Closing, this proposal has been accepted. See https://github.com/stencil-community/stencil-helmet for the new community based repo
